export const SEMESTER_REGISTRATION_STATUS: string[] = [
  'UPCOMING',
  'ONGOING',
  'ENDED',
];

export const REGISTRATION_STATUS = {
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  ENDED: 'ENDED',
};
